### ISSUE TITLE
你好，pip install -e PaddleRS/   时报错

### ISSUE THREAD

**Issue by MMM-YS** [PaddleCV-SIG/GeoView#66]
× python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      2023-04-10 10:32:53,466-WARNING: post-quant-hpo is not support in system other than linux
      running egg_info
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "M:\AAAjob\AI\GeoView\PaddleRS\setup.py", line 26, in <module>
          setuptools.setup(
        File "M:\software\anaconda\envs\paddle\lib\site-packages\setuptools\__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "M:\software\anaconda\envs\paddle\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "M:\software\anaconda\envs\paddle\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "M:\software\anaconda\envs\paddle\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "M:\software\anaconda\envs\paddle\lib\site-packages\setuptools\dist.py", line 1221, in run_command
          super().run_command(command)
        File "M:\software\anaconda\envs\paddle\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.ensure_finalized()
        File "M:\software\anaconda\envs\paddle\lib\site-packages\setuptools\_distutils\cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "M:\software\anaconda\envs\paddle\lib\site-packages\setuptools\command\egg_info.py", line 220, in finalize_options
          parsed_version = packaging.version.Version(self.egg_version)
        File "M:\software\anaconda\envs\paddle\lib\site-packages\setuptools\_vendor\packaging\version.py", line 197, in __init__
          raise InvalidVersion(f"Invalid version: '{version}'")
      setuptools.extern.packaging.version.InvalidVersion: Invalid version: 'develop'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.

**Comment by Bobholamovic** [comment]
你好，可尝试将下面位置的`develop`修改为`0.0.0.dev`以绕过新版本setuptools的PEP440检查：

https://github.com/PaddlePaddle/PaddleRS/blob/da1a7457e37b7a70ccf6045f4be08077efa1e0d4/paddlers/__init__.py#L15

**Comment by MMM-YS** [comment]
谢谢，已解决
