### ISSUE TITLE
你好，我在使用时出现了 未检测到模型文件，请查看上传目录是否有误

### ISSUE THREAD

**Issue by wufxgtihub123** [PaddleCV-SIG/GeoView#70]
我已经按照文档在model文件夹下导入了目标检测模型ppyolo，然后才启动的项目，但是前端页面仍然报错
未检测到模型文件，请查看上传目录是否有误
![image](https://github.com/PaddleCV-SIG/GeoView/assets/74227869/3f6ff20a-0879-452d-80bc-5c3634931f4b)

**Comment by jscslld** [comment]
![image](https://github.com/PaddleCV-SIG/GeoView/assets/13760010/9141d4a4-6f5b-469c-b683-30b684e1a471)
把这五个文件放到ppyolo文件夹内

**Comment by wufxgtihub123** [comment]
@jscslld 我已经把模型放入到ppyolo下面了，但还是检测不到的
![image](https://github.com/PaddleCV-SIG/GeoView/assets/74227869/26155c00-6251-4d36-bbe1-8a8f7484680d)

**Comment by wufxgtihub123** [comment]
也重启了服务，但没起作用

**Comment by wufxgtihub123** [comment]
@jscslld 我是按照这种方式做的，ppyolo文件夹在object_detection下，并且里面包含模型参数文件
![image](https://github.com/PaddleCV-SIG/GeoView/assets/74227869/cc698720-5fd0-4507-956c-9ce141219086)

**Comment by wufxgtihub123** [comment]
我想问一下加载存放模型的路径文件是在哪个python文件下看的呢？

**Comment by terayco** [comment]
@wufxgtihub123 在此路径查看：backend/applications/api/model.py

**Comment by wufxgtihub123** [comment]
@terayco 我又安装文档重现安装了一次，模型放的路径是对的，但是还是报一样的问题，找不到模型，不知道该如何解决

**Comment by terayco** [comment]
@wufxgtihub123 是所有功能都这样吗，还是只有目标检测这样呢？

**Comment by wufxgtihub123** [comment]
@terayco 所有的模型都是这个样子

**Comment by terayco** [comment]
@wufxgtihub123 有可能是新版PaddleRS导出模型和我们当时GeoView使用的版本导出模型方式不一致造成的问题，你可以把paddleRS版本回退一下试试，我们后续也会查看的，但今天有点忙可能没空。。你可以试试如果不行再反馈给我们，实在抱歉哈~

**Comment by wufxgtihub123** [comment]
@terayco 你好，请问如何回退PaddleRS的版本呢？

**Comment by terayco** [comment]
@wufxgtihub123 使用PaddleRS官网发布的1.0正式版本即可

**Comment by wufxgtihub123** [comment]
@terayco 你好，我将PaddleRS的版本回退到1.0以后还用然后又执行的pip install requirement.txt 和pip install -e PaddleRS/ 然后又使用python app.py 等重启的前后端项目，但是还是报之前同样的问题，模型找不到

**Comment by czfree** [comment]
额，同样问题，
<img width="1041" alt="image" src="https://github.com/PaddleCV-SIG/GeoView/assets/13724458/6529fa15-c0b0-4bf3-9859-2fd8ef721238">
直接使用GeoView提供的模型也是这样。

**Comment by czfree** [comment]
我也有这个问题，后面发现是因为web前端访问python后端失败导致的（我服务搭建在服务器上，本地用浏览器访问，host地址出错），你可以打开浏览器控制台，看下有无网络报错。

**Comment by jscslld** [comment]
> 我也有这个问题，后面发现是因为web前端访问python后端失败导致的（我服务搭建在服务器上，本地用浏览器访问，host地址出错），你可以打开浏览器控制台，看下有无网络报错。

有可能的，如果部署在云主机上的话，需要将config.yml中的0.0.0.0修改为实际IP。修改后，先重启后端（系统会自动为前端生成配置文件），然后再启动前端，这样网络报错应该就可以解决了

**Comment by lishulincug** [comment]
识别相对路径出错，这里，if后就没进去，这样写相对路径是得配置才能识别
    if os.path.exists("model/{}".format(model_type)):
        for dirname in os.listdir("model/{}".format(model_type)):
            if not os.path.isdir("model/{}/{}".format(model_type, dirname)):

**Comment by wufxgtihub123** [comment]
> h

请问，那这种问题该怎么解决呢？

**Comment by wufxgtihub123** [comment]
@lishulincug 请问出现识别路径的问题该怎么解决呢？

**Comment by wufxgtihub123** [comment]
@czfree 你好，请问访问不到后端你是怎么解决的呢？

**Comment by wufxgtihub123** [comment]
@jscslld 你好，请问我检查了一下模型路径是没有问题的，然后报后端错误：（pymysql.err.OperationalError)(1045,"Access denied for user 'root'@'localhost'(using password: YES)") (Background on this error at https://sqlalche.me/e/20/e3q8) 这个是什么原因呢？我就按照文档，添加的mysql配置，我用navicat都可以连上mysql

**Comment by jscslld** [comment]
> @jscslld 你好，请问我检查了一下模型路径是没有问题的，然后报后端错误：（pymysql.err.OperationalError)(1045,"Access denied for user 'root'@'localhost'(using password: YES)") (Background on this error at https://sqlalche.me/e/20/e3q8) 这个是什么原因呢？我就按照文档，添加的mysql配置，我用navicat都可以连上mysql

请问你的root密码中带特殊字符吗，如果带的话，需要使用develop分支

**Comment by wufxgtihub123** [comment]
@jscslld 带@这种字符，请问该怎么使用分支呢？

**Comment by jscslld** [comment]
git checkout develop

**Comment by wufxgtihub123** [comment]
@jscslld 那我把mysql账户密码改为不带特殊字符的，是否可以呢？ 这样不用拉分支了

**Comment by jscslld** [comment]
可以的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月19日(周五) 下午5:48
收件人: ***@***.***&gt;;
抄送: "Lu ***@***.******@***.***&gt;;
主题: Re: [PaddleCV-SIG/GeoView] 你好，我在使用时出现了 未检测到模型文件，请查看上传目录是否有误 (Issue #70)




 
@jscslld 那我把mysql账户密码改为不带特殊字符的，是否可以呢？ 这样不用拉分支了

**Comment by wufxgtihub123** [comment]
@jscslld 你好，我更改了数据库中的密码不包含特殊字符，但是还是报了（pymysql.err.OperationalError)(1045,"Access denied for user 'root'@'localhost'(using password: YES)") (Background on this error at https://sqlalche.me/e/20/e3q8)   请问我该如何定位到报错信息的具体位置或者是报错的具体原因是什么呢？

**Comment by jscslld** [comment]
如果要看详细的报错信息，还是需要拉取develop分支，然后开启debug模式

**Comment by wufxgtihub123** [comment]
@jscslld 你好，现在我工程跑起来之后，在做目标检测模块的时候前端页面报错了：uncaught runtime errors: 
ERROR : unknow promise rejection reason
 at handleError (webpack-internal:///./node_modules/webpack-dev-server/client/overlay.js:299:58
 at eval (webpack-internal:///./node_modules/webpack-dev-server/client/overlay.js:322:7)     我是直接按照官网教程的进行编译打包，不知道这个报错是怎么回事？

**Comment by yibaikuai** [comment]
@wufxgtihub123 请问你的服务部署在云主机上吗，使用其他功能时报错吗，能截图看看报错时浏览器控制台网络部分的信息吗，像这样 [img](https://user-images.githubusercontent.com/90198481/241355017-42ee16b7-3696-4854-9c03-7899cdb0ac3c.png)

**Comment by wufxgtihub123** [comment]
@jscslld 你好，我在拉取了develop分支下的代码后，启动服务后使用变化检测时，我上传的图像形如下面的：
![image](https://github.com/PaddleCV-SIG/GeoView/assets/74227869/2b8ec0f9-1e71-4940-b0b2-73e9d0da2136)
ran然后执行就报错了：
![image](https://github.com/PaddleCV-SIG/GeoView/assets/74227869/8fbb1c06-e6f3-4122-b006-44ddf05300e9)
请问是哪里的问题呢?

**Comment by jscslld** [comment]
你把config.yml文件里的debug改成true，然后重新运行后端。把后端打印出的traceback信息贴上来看下。

**Comment by wufxgtihub123** [comment]
@jscslld  @lishulincug @Bobholamovic 你好，再次执行上面的步骤，报错是：
![image](https://github.com/PaddleCV-SIG/GeoView/assets/74227869/a6e73e47-2392-4d1a-9be7-d7855cbf1a99)，是不是变化检测的结果是灰度图，然后这个skimage 库并不能保存灰度图，需要转为rgb啊？

**Comment by jscslld** [comment]
> @jscslld @lishulincug @Bobholamovic 你好，再次执行上面的步骤，报错是： ![image](https://user-images.githubusercontent.com/74227869/241697184-a6e73e47-2392-4d1a-9be7-d7855cbf1a99.png)，是不是变化检测的结果是灰度图，然后这个skimage 库并不能保存灰度图，需要转为rgb啊？

有这种可能，你上传的图象是灰度图还是RGB的？因为我从Github下载到的测试图片是PNG类型的图片，在本地测试好像没问题。

**Comment by jscslld** [comment]
> @jscslld @lishulincug @Bobholamovic 你好，再次执行上面的步骤，报错是： ![image](https://user-images.githubusercontent.com/74227869/241697184-a6e73e47-2392-4d1a-9be7-d7855cbf1a99.png)，是不是变化检测的结果是灰度图，然后这个skimage 库并不能保存灰度图，需要转为rgb啊？

已修复该BUG，等待PR #72 合并
