### ISSUE TITLE
APP不存在，AK有误请检查再重试

### ISSUE THREAD

**Issue by mutou-ship** [PaddleCV-SIG/GeoView#95]
![`O{8`52J0V2WY$MVSS )(Q](https://github.com/PaddleCV-SIG/GeoView/assets/173971056/0b7ca565-6192-44a3-95d5-a843562f9dbb)
点击在线地图显示APP不存在，AK有误请检查再重试，详情查看：http://lbsyun.baidu.com/apiconsole/key#。
并显示错误：
ERROR
Script error.
    at handleError (webpack-internal:///./node_modules/webpack-dev-server/client/overlay.js:299:58)
    at eval (webpack-internal:///./node_modules/webpack-dev-server/client/overlay.js:318:7)

config.yaml文件改成了
port:
  backend: 5008
  frontend: 3000
host:
  backend: 0.0.0.0
  frontend: 0.0.0.0
baidu_map:
  access_key: nV1wFZZEfewhY4thlMPUSp（我改的AK）
debug: true

**Comment by jscslld** [comment]
你是在https://lbsyun.baidu.com/申请的AK吗？

**Comment by yibaikuai** [comment]
[https://lbsyun.baidu.com/apiconsole/key/create#/home](url) 服务端AK不支持浏览器端使用
![屏幕截图 2024-09-08 183256](https://github.com/user-attachments/assets/07a68796-a747-4a8d-ba4b-37ec4d878e9e)
